config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users

  get 'tags/:tag', to: 'dashboard#index', :as => 'tag'
  root to: "dashboard#index", :as => 'dashboard'

end

app/models/post.rb
class Post < ActiveRecord::Base

  validate :post_quota, :on => :create, if: :user
  validates :title, :description, presence: true
  validates :title, :description, uniqueness: true
  validates :user, presence: true
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings

  #all_tags method to map all tags separated by coma
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end

  private

  def post_quota
    if user.posts.today.count >= 1
      errors.add(:base, "#{user.email} can only post once a day")
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts do
    def today
      where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now))
    end
  end

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@posts = Post.order("created_at DESC")

    if params[:tag]
      @post_by_date = Post.tagged_with(params[:tag]).order("created_at DESC").group_by { |i| i.created_at.to_date }
    else
      @post_by_date = @posts.group_by { |i| i.created_at.to_date }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    #only showing the current user's posts
    @posts_by_user = Post.where(:user_id => current_user)
    @post_by_date = @posts_by_user.order("created_at DESC").group_by { |i| i.created_at.to_date }
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.js { @posts = Post.all, flash[:notice] = "Post created successfully"}
      else
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.js { @posts = Post.all, flash[:notice] = "Post updated successfully"}
      else
        format.js { render :edit}
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_url, notice: 'Post successfully removed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post).permit(:title, :description, :all_tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	#turns all the tags into html hyperlinks
	def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(" ") 
  end

  def date_check_format(date)
	  if date == Date.today
      "Today"
      elsif date == Date.yesterday
        "Yesterday"
      else
        date.strftime("%d/%m/%y")
    end
  end
end

app/views/dashboard/index.html.erb
<div class="posts">
  <h2>Dashboard</h2>

  <div class="alert-container">
    <% if notice %>
      <p class="alert alert-success fade in"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger fade in"><%= alert %></p>
    <% end %>
  </div>
  
  <%= render 'posts/post_by_date'%>

  <div id="post-modal" class="modal fade"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="nav">
    <span>Post App</span>
    <div class="tabs">
      <ul>
       <%= link_to 'Dashboard', dashboard_path %>
       <%= link_to 'My Posts', posts_path %>
       <%= link_to 'New Post', new_post_path, remote: true %>

        <li class="pull-right">
          <p>
          <% if user_signed_in?%>
            Welcome, <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
          </p>
        </li>
      </ul>
    </div>
  </div>

  <%= yield %>

  </body>
</html>

app/views/posts/_edit.html.erb
<%= render 'form' %>

app/views/posts/_form.html.erb
<div class="modal-dialog">
  <%= form_for (@post), remote: true, html: {style: "display-inline;"} do |f| %>
  <div class="modal-content">
    <div class="modal-header">
      <h4>New Post</h4>
    </div>
    <div class="modal-body">
      <% if @post.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>
          <ul>
           <% @post.errors.full_messages.each do |message| %>
             <li><%= message %></li>
            <% end %>
            </ul>
          </div>
      <% end %>
      <div class="form-horizontal">
        <div class="form-group">
          <div class="col-sm-1"></div>
          <div class="col-sm-2">
            <%= f.label :title %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :title, class: 'form-control', placeholder: 'Enter a title' %>
          </div>
          <div class="col-sm-1"></div>
        </div>
        <div class="form-group">
          <div class="col-sm-1"></div>

          <div class="col-sm-2">
            <%= f.label :description %> <br>
          </div>
          <div class="col-sm-8">
            <%= f.text_area :description, class: 'form-control', rows:10, placeholder: 'Your post'%>
          </div>
          <div class="col-sm-1"></div>
        </div>

        <div class="form-group">
          <div class="col-sm-1"></div>
          <div class="col-sm-2"><%= f.label :tags %></div>
          <div class="col-sm-8">
            <%= f.text_field :all_tags, class:'tag-input', placeholder: "Tags separated with coma"%>
          </div>
          <div class="col-sm-1"></div>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/posts/_new.html.erb
<%= render 'form' %>

app/views/posts/_post.html.erb
<div class="row">
  <div class="col-sm-2"></div>
  <div class="post-container col-sm-7">
    <div class="post-header">
        <%= post.user %>
      <div class="crud-menu">
        <ul>
          <li><%= link_to edit_post_path(post), remote: true do %>
            <i class="glyphicon glyphicon-edit"></i>
           <% end %>
          </li>
          <li><%= link_to post, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="glyphicon glyphicon-trash"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <div class="post-body">
      <dl>
        <dt>
          <h2><%= post.title %></h2>
        </dt>
        <dd>
          <span class="post-description"><%= post.description.html_safe %></span><br>
          <span class="post-created">- <%= time_ago_in_words(post.created_at)%> ago</span>
          <div class="tag-container">
            <span> <i class="glyphicon glyphicon-tags"></i> <%= raw tag_links(post.all_tags) %></span>         
          </div>
        </dd>
      </dl>
    </div>
    <div class="post-footer"></div>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/posts/_post_by_date.html.erb
<div class="container-fluid post-container">
  <% @post_by_date.each do |date, posts|%>
    <h3><%= date_check_format(date)%></h3>
    <%= render posts %>
  <% end %>
</div>

app/views/posts/_posts.html.erb
<%= render @posts %>

app/views/posts/_save.js.erb
$(".post-container").html("<%= escape_javascript(render 'posts') %>")
$("#post-modal").modal("hide")
$(".alert-container").html("<%= flash[:notice] %>");

app/views/posts/create.js.erb
window.location = "<%= dashboard_url %>"
$(".alert-container").html("<%= flash[:notice] %>");

app/views/posts/edit.js.erb
$("#post-modal").html("<%= escape_javascript(render 'edit') %>")
$("#post-modal").modal("show")

$('.tag-input').selectize({
  delimiter: ',',
  persist: false,
  create: function(input) {
    return {
        value: input,
        text: input
    }
  }
});

app/views/posts/index.html.erb
<div class="posts">
  <h2>Listing My Posts</h2>

  <div class="alert-container">
    <% if notice %>
      <p class="alert alert-success fade in"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger fade in"><%= alert %></p>
    <% end %>
  </div>

  <%= render 'posts/post_by_date'%>

  <div id="post-modal" class="modal fade"></div>
</div>

app/views/posts/new.js.erb
$("#post-modal").html("<%= escape_javascript(render 'new') %>")
$("#post-modal").modal("show")

$('.tag-input').selectize({
  delimiter: ',',
  persist: false,
  create: function(input) {
    return {
        value: input,
        text: input
    }
  }
});

app/views/posts/update.js.erb
window.location = "<%= dashboard_url %>"